CHICKEN_CLEAN		:= chicken-clean
MARKDOWN_SVNWIKI	:= markdown-svnwiki
README_MD		:= README.md
README_ORG		:= README.org
README_SVNWIKI  	:= README.svnwiki
SALMONELLA		:= salmonella
SALMONELLA_LOG		:= salmonella.log

all: doc test

clean:
	$(CHICKEN_CLEAN)
	rm -f $(SALMONELLA_LOG)

doc: $(README_SVNWIKI)

# Note: README.md and README.svnwiki will be checked in to version control,
#       but as they are both automatically generated there is no use diffing them
#       (they will differ every time at least with autogenerated org-id's).
#
#       The source of truth for them is the README.org file
$(README_SVNWIKI): $(README_MD)
	$(MARKDOWN_SVNWIKI) $< > $@

test:
	$(SALMONELLA)
